@startuml
actor Administrator as Admin

Admin -> System: Request List of All Vaccines
activate System

System -> Database: Retrieve List of Vaccines
Database --> System: List of Vaccines Grouped by Type\nand Sorted Alphabetically by Name

System --> Admin: Display List of Vaccines

deactivate System
@enduml
