@startuml
actor Administrator as Admin

Admin -> System: Specify New Vaccine Type
activate System

System -> System: Validate Mandatory Attributes\n(Code, Short Description, Vaccine Technology)
alt All attributes valid
    System -> System: Validate Code Format\n(Five alphanumeric characters)
    alt Code format valid
        System -> System: Validate Vaccine Technology\n(From https://www.pfizer.com/...)
        alt Vaccine Technology valid
            System -> Database: Check Code Uniqueness
            Database --> System: Unique Code
            alt Code is unique
                System -> System: Save Vaccine Type
                System --> Admin: Confirmation Message
            else Code is not unique
                System --> Admin: Error Message\n(Code must be unique)
            end
        else Vaccine Technology invalid
            System --> Admin: Error Message\n(Invalid Vaccine Technology)
        end
    else Code format invalid
        System --> Admin: Error Message\n(Invalid Code Format)
    end
else Mandatory attributes missing
    System --> Admin: Error Message\n(Missing Mandatory Attributes)
end

deactivate System
@enduml