```plantuml
@startuml

title Domain Model US011

class Administrator {
  +manages(o) : Vaccine
}

class Vaccine {
  +Id : int
  +Name : String
  +Brand : String
  +VaccineType : String
}

Administrator --> "manages" Vaccine

@enduml